include: package:lints/recommended.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    prefer_final_locals: true
    unawaited_futures: true
